spring:

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: doctor-service
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/api/v1/doctor
                - Path=/api/v1/doctor/**

            - id: appointment-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/appointment
                - Path=/api/v1/appointment/**

            - id: patient-service
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path=/api/v1/patient
                - Path=/api/v1/patient/**

          default-filters:
            - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 7000

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/