spring:
  application:
    name: Config-Server

  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kalanaCwarnakulasooriya/Health-Configurations.git
        native:
          search-locations:
            - classpath:/configurations
            - classpath:/configurations/platform
            - classpath:/configurations/services

server:
  port: 9000

